---
title: "git_00"
author: "Roselyn Villatoro"
date: "Sep 12, 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

Little Birds are diningWarily and well,  
Hid in mossy cell:  
Hid, I say, by waiters. 
Gorgeous in their gaiters -  
I've a Tale to tell.  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Some say the world will end in fire,  
Some say in ice.  
From what I've tasted of desire  
I hold with those who favor fire.  
But if it had to perish twice,  
I think I know enough of hate  
To say that for destruction ice  
Is also great  
And would suffice.  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.   

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there   
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

The highway is full of big cars going nowhere fast  
And folks is smoking anything that’ll burn  
Some people wrap their lives around a cocktail glass  
And you sit wondering  
where you’re going to turn.  
I got it.  
Come. And be my baby.  

Some prophets say the world is gonna end tomorrow.  
But others say we’ve got a week or two.  
The paper is full of every kind of blooming horror  
And you sit wondering  
what you’re gonna do.  
I got it.  
Come. And be my baby.  
